#!/bin/bash -x

# Generate LibreOffice AppImage
# by Antonio Faccioli
# Based on script by Simon Peter
# Released under the Mozilla Public License Version 2.0
# http://www.libreoffice.org/about-us/licenses/

libreVersion=$1
arch=$2
language=$3
optHelp={$4-N}

standard=(en-GB it ar zh-CN zh-TW fr de ja ko pt pt-BR es ru)
full=(af am ar as ast be bg bn-IN bn bo br brx bs ca-valencia ca cs cy da de dgo dz el en-GB en-ZA eo es et eu fa fi fr ga gd gl gu gug he hi hr hsb hu id is it ja ka kk km kmr kn ko kok ks lb lo lt lv mai mk ml mn mni mr my nb ne nl nn nr nso oc om or pa-IN pl pt-BR pt qtz ro ru rw sa-IN sat sd si sid sk sl sq sr-Latn sr ss st sv sw-TZ ta te tg th tn tr ts tt ug uk uz ve vec vi xh zh-CN zh-TW zu)

if [[ $arch == *"x86-64"* ]] ; then
	pathArch="x86_64"
fi

APP=LibreOffice

set +e

if [[ $libreVersion == *"fresh"* ]] ; then
    nrVersion=$(wget -q "https://www.libreoffice.org/download/libreoffice-fresh/" -O - | grep -o -e "/dl/src/.*/all/" | cut -d "/" -f 4 | head -n 1)
    path="https://download.documentfoundation.org/libreoffice/stable/"$nrVersion"/deb/"$pathArch"/"
	package="LibreOffice_"$nrVersion"_Linux_"$arch"_deb.tar.gz"
elif [[ $libreVersion == *"still"* ]] ; then
    nrVersion=$(wget -q "https://www.libreoffice.org/download/libreoffice-still/" -O - | grep -o -e "/dl/src/.*/all/" | cut -d "/" -f 4 | head -n 1)
    path="https://download.documentfoundation.org/libreoffice/stable/"$nrVersion"/deb/"$pathArch"/"
	package="LibreOffice_"$nrVersion"_Linux_"$arch"_deb.tar.gz"
else
    nrVersion=$libreVersion 
    path="https://downloadarchive.documentfoundation.org/libreoffice/old/"$nrVersion"/deb/"$pathArch"/"
    package="LibreOffice_"$nrVersion"_Linux_"$arch"_deb.tar.gz"
fi
      
LibODownloadLink=$path$package

if [[ $optHelp == *"Y"* ]] ; then    
VERSION=$nrVersion"."$language".help"
else
VERSION=$nrVersion"."$language
fi

mkdir -p ./$APP/$APP.AppDir
cd ./$APP

wget -c $LibODownloadLink

if [[ $language == *"standard"* ]] ; then
	for element in ${standard[*]}; 
        do 
           langPackage="LibreOffice_"$nrVersion"_Linux_"$arch"_deb_langpack_"$element".tar.gz"
           wget -c $path$langPackage 
        done
elif [[ $language == *"full"* ]] ; then
	for element in ${full[*]}; 
        do 
           langPackage="LibreOffice_"$nrVersion"_Linux_"$arch"_deb_langpack_"$element".tar.gz"
           wget -c $path$langPackage
        done
else
    langPackage="LibreOffice_"$nrVersion"_Linux_"$arch"_deb_langpack_"$language".tar.gz"
    wget -c $path$langPackage
fi

if [[ $optHelp == *"Y"* ]] ; then
    if [[ $language == *"standard"* ]] ; then
	     for element in ${standard[*]}; 
             do 
                helpPackage="LibreOffice_"$nrVersion"_Linux_"$arch"_deb_helppack_"$element".tar.gz"
                wget -c $path$helpPackage
         done
    elif [[ $language == *"full"* ]] ; then
	     for element in ${full[*]}; 
             do 
               helpPackage="LibreOffice_"$nrVersion"_Linux_"$arch"_deb_helppack_"$element".tar.gz"
               wget -c $path$helpPackage
         done
    else
         helpPackage="LibreOffice_"$nrVersion"_Linux_"$arch"_deb_langpack_"$language".tar.gz"
         wget -c $path$helpPackage
    fi
fi
                          


for i in *.tar.gz; do tar xfvz $i; done

cd $APP.AppDir/

find ../ -name *.deb -exec dpkg -x \{\} . \;

find . -type f -iname "bootstraprc" -exec sed -i "s|^UserInstallation=.*|UserInstallation=\$SYSUSERCONFIG/libreoffice/$nrVersion|g" {} +

find . -name startcenter.desktop -exec cp \{\} . \;

sed -i -e 's|Name=.*|Name=LibreOffice|g' startcenter.desktop

find -name *startcenter.png -path *hicolor*48x48* -exec cp \{\} . \;

BINARY=$(cat *.desktop | grep "Exec=" | head -n 1 | cut -d "=" -f 2 | cut -d " " -f 1)

mkdir -p usr/bin/
cd usr/bin/
rm ./$BINARY
find ../../opt -name soffice -path *program* -exec ln -s \{\} ./$BINARY \;
cd ../../

wget -c https://github.com/probonopd/AppImageKit/releases/download/6/AppRun_6-x86_64 -O AppRun # 64-bit
chmod a+x AppRun

cd ..

URL="https://github.com/probonopd/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
wget -c "$URL" -O appimagetool
chmod a+x ./appimagetool
set +x

VERSION=$VERSION ./appimagetool --comp xz -v ./$APP.AppDir/

set -x
mkdir -p ../out/ || true
mv *.AppImage* ../out/


#cp ../out/LibreOffice* /var/www/html/libreoffice/stable/
#rm -R ../LibreOffice*
#rm -R ../out
